# =============================================================================
# Acond TČ - Přidej tyto řádky do configuration.yaml
# =============================================================================

modbus: !include modbus_acond.yaml
template: !include template_sensors_acond.yaml
shell_command: !include shell_command_acond.yaml
automation: !include automation_acond.yaml
input_number: !include input_number_acond.yaml
input_boolean: !include input_boolean_acond.yaml
